# permissions for end users to edit tunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cftunnel-argo-controller
    app.kubernetes.io/managed-by: kustomize
  name: tunnels-editor-role
rules:
- apiGroups:
  - cftunnel-argo.controller.cftunnel-argo.controller
  resources:
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cftunnel-argo.controller.cftunnel-argo.controller
  resources:
  - tunnels/status
  verbs:
  - get
